# Free software (c) 2011 ALICE A.I. Foundation. 
# This program is open source code released under
# the terms of the GNU General Public License 
# as published by the Free Software Foundation. 
# Complies with AIML 1.0 Tag Set Specification
# as adopted by the ALICE A.I. Foundation. 
#
# Last modified 11/27/2011

learn "FOUR CULTURES" do
 [
 "France",
 "Vietnam",
 "Thailand",
 "Algeria",
 ]
end

learn "ONE CULTURES" do
 [
 "Canada",
 "Holland",
 "New England",
 "New Zealand",
 "the Amish",
 "the Puritains",
 "Switzerland",
 ]
end

learn "FIVE CULTURES" do
	"England"
end

learn "SIX CULTURES" do
 [
 "Singapore",
 "China",
 "Germany",
 "Russia",
 ]
end

learn "RANDOM FOURS" do
 [
 "Photographer Diane Arbus",
 "Painter Francis Bacon",
 "John Barrymore",
 "Charles Baudelaire",
 "Ingmar Bergman",
 "Poet John Berryman",
 "Director Peter Bogdanovich",
 "Marlon Brando",
 "Richard Brautigan",
 "Jackson Browne",
 "Raymond Burr",
 "Singer Kate Bush",
 "Mary Chapin Carpenter",
 "Prince Charles",
 "Eric Clapton",
 "Kurt Cobain",
 "Leonard Cohen",
 "Judy Collins",
 "James Dean",
 "Johnny Depp",
 "Neil Diamond",
 "Isak Dinesen",
 "Michael Dorris",
 "French novelist Marguerite Duras",
 "Bob Dylan",
 "Judy Garland",
 "Martha Graham",
 "Singer Nanci Griffith",
 "Billie Holliday",
 "Lena Horne",
 "Julio Iglesias",
 "Michael Jackson",
 "Jewel",
 "Janis Joplin",
 "Naomi Judd",
 "Harvey Keitel",
 "Jack Kerouac",
 "Poet Philip Larkin",
 "Charles Laughton",
 "T. E. Lawrence",
 "Vivien Leigh",
 "John Malkovich",
 "Marcello Mastroianni",
 "Author Mary McCarthy",
 "Carson McCullers",
 "Rod McKuen",
 "Thomas Merton",
 "Author Yukio Mishima",
 "Joni Mitchell",
 "Jim Morrison",
 "Morrissey",
 "Edvard Munch",
 "Liam Neeson",
 "Mike Nichols",
 "Stevie Nicks",
 "Author Anais Nin",
 "Nick Nolte",
 "Laurence Olivier",
 "Edith Piaf",
 "Sylvia Plath",
 "Edgar Allen Poe",
 "Novelist Anne Rice",
 "Arthur Rimbaud",
 "Francoise Sagan",
 "Poet Anne Sexton",
 "Percy Shelley",
 "Simone Signoret",
 "Singer Paul Simon",
 "Edna St. Vincent Millay",
 "August Strindberg",
 "Singer James Taylor",
 "Spencer Tracy",
 "Vincent Van Gogh",
 "Suzanne Vega",
 "Author Robert James Waller",
 "Alan Watts",
 "Orson Welles",
 "Australian novelist Patrick White",
 "Tennessee Williams",
 "Kate Winslet",
 "Virginia Woolf",
 "Neil Young",
 "Richard Wallace",
 ]
end

learn "RANDOM EIGHTS" do
 [
 "the cultural aura of Serbia",
 "the culture of the Mafia",
 "Lawyer Leslie Abramson",
 "Gloria Allred",
 "Director Robert Altman",
 "Edward Asner",
 "Kemal Ataturk",
 "F. Lee Bailey",
 "Actor Joe Don Baker",
 "Lucille Ball",
 "Charles Barkley",
 "Richard Belzer",
 "Humphrey Bogart",
 "Napoleon Bonaparte",
 "Charles Bronson",
 "James Brown",
 "Football's Jim Brown",
 "Pat Buchanan",
 "Richard Burton",
 "Johnny Cash",
 "John Cassavetes",
 "Fidel Castro",
 "Eldridge Cleaver",
 "Ty Cobb",
 "Sean Connery",
 "Jimmy Connors",
 "Robert Conrad",
 "Matt Damon",
 "Brian Dennehy",
 "Alan Dershowitz",
 "Danny DeVito",
 "Football's Mike Ditka",
 "Bob Dole",
 "Sam Donaldson",
 "Kirk Douglas",
 "Michael Douglas",
 "Morton Downey Jr.",
 "Fred Dryer",
 "Boxer Roberto Duran",
 "Author Harlan Ellison",
 "Milton Erickson",
 "Moshe Feldenkrais",
 "Actress Linda Fiorentino",
 "Indira Gandhi",
 "Apache warrior Geronimo",
 "John Gotti",
 "George Gurdjieff",
 "the Hell's Angels",
 "Ernest Hemingway",
 "Jimmy Hoffa",
 "Opera singer Marilyn Horne",
 "Saddam Hussein",
 "Director John Huston",
 "Laura Ingraham",
 "Joan Jett",
 "Lyndon Johnson",
 "Carlos Casteneda's Don Juan",
 "Brian Keith",
 "Nikita Khrushchev",
 "Evel Knievel",
 "Michael Landon",
 "Rush Limbaugh",
 "John Lydon (Johnny Rotten)",
 "Norman Mailer",
 "Mao Tse-tung",
 "Wynton Marsalis",
 "Lee Marvin",
 "Tycoon Robert Maxwell",
 "Malcolm McDowell",
 "John McEnroe",
 "Mark McGwire",
 "Golda Meir",
 "Comedian Dennis Miller",
 "Robert Mitchum",
 "Actor Judd Nelson",
 "George Patton",
 "Director Sam Peckinpah",
 "Sean Penn",
 "Gestalt therapist Fritz Perls",
 "Julia Phillips",
 "Actress Julianne Phillips",
 "Suzanne Pleshette",
 "Queen Latifah",
 "Dixy Lee Ray",
 "Ann Richards",
 "Geraldo Rivera",
 "Theodore Roosevelt",
 "Axl Rose",
 "Mickey Rourke",
 "Colonel Harland Sanders",
 "Telly Savalas",
 "Baseball's Marge Schott",
 "George C. Scott",
 "Maurice Sendak",
 "Tupac Shakur",
 "Frank Sinatra",
 "Grace Slick",
 "Guardian Angel Curtis Sliwa",
 "Joseph Stalin",
 "John Sununu",
 "Tamerlane",
 "Charlize Theron",
 "Rip Torn",
 "Donald Trump",
 "Pancho Villa",
 "Ken Wahl",
 "George Wallace",
 "Mike Wallace",
 "Denzel Washington",
 "John Wayne",
 "Ted Williams",
 "Debra Winger",
 "Zorba the Greek",
 ]
end

learn "RANDOM SEVENS" do
 [
 "Paul Allen",
 "Comedian Steve Allen",
 "Comedian Tim Allen",
 "Desi Arnaz",
 "Richard Avedon",
 "Robert Ballard",
 "Honore Balzac",
 "Humorist Dave Barry",
 "Jack Benny",
 "Chuck Berry",
 "Jacqueline Bisset",
 "Poet Robert Bly",
 "Sonny Bono",
 "Comedienne Elayne Boosler",
 "Musical comedian Victor Borge",
 "Football's Terry Bradshaw",
 "Kenneth Branagh",
 "Richard Branson",
 "Jimmy Buffett",
 "Michael Caine",
 "Mythologist Joseph Campbell",
 "Pierre Cardin",
 "Jackie Chan",
 "Chevy Chase",
 "Maurice Chevalier",
 "George Clooney",
 "Buffalo Bill Cody",
 "Joan Collins",
 "Director Francis Ford Coppola",
 "Filmmaker Roger Corman",
 "MTV's Dan Cortese",
 "Katie Couric",
 "David Crosby",
 "e.e. cummings",
 "Tony Curtis",
 "Roger Daltry",
 "Philosopher Gerard Depardieu",
 "Diderot",
 "QVC resident Barry Diller",
 "Hugh Downs",
 "Michael Eisner",
 "Douglas Fairbanks Jr.",
 "Federico Fellini",
 "Sarah Ferguson",
 "Physicist Richard Feynman",
 "Errol Flynn",
 "Peter Fonda",
 "Malcolm Forbes",
 "George Foreman",
 "Bob Fosse",
 "Matthew Fox",
 "Michael J. Fox",
 "Author Robert Fulghum",
 "Clark Gable",
 "Ava Gardner",
 "Carlos Casteneda's Don Genaro",
 "John Gielgud",
 "Dizzy Gillespie",
 "Newt Gingrich",
 "Goethe",
 "Ruth Gordon",
 "Cary Grant",
 "Andre Gregory",
 "George Hamilton",
 "Tom Hanks",
 "Richard Harris",
 "Goldie Hawn",
 "Actress Marilu Henner",
 "Abbie Hoffman",
 "Pianist Vladimir Horowitz",
 "Ron Howard",
 "Lauren Hutton",
 "Self-help author Gerald Jampolsky",
 "Derek Jarman",
 "Thomas Jefferson",
 "Steve Jobs",
 "Magic Johnson",
 "Architect Phillip Johnson",
 "Jerry Jones",
 "King Juan Carlos of Spain",
 "Actress Carol Kane",
 "Michael Keaton",
 "John F. Kennedy",
 "Ken Kesey",
 "Comedian Alan King",
 "Don King",
 "CNN's Larry King",
 "Comedian Robert Klein",
 "Director David Lean",
 "Timothy Leary",
 "Director Barry Levinson",
 "Puppeteer Shari Lewis",
 "Artist Roy Lichtenstein",
 "Loretta Lynn",
 "Football's John Madden",
 "Director Louis Malle",
 "Singer Meat Loaf",
 "Author Henry Miller",
 "Yves Montand",
 "Dudley Moore",
 "Jeanne Moreau",
 "Robert Morley",
 "Eddie Murphy",
 "Jack Nicholson",
 "Leslie Nielsen",
 "Donald O'Connor",
 "Peter O'Toole",
 "Luciano Pavarotti",
 "Author Joseph Chilton Pearce",
 "Regis Philbin",
 "Bronson Pinchot",
 "Brad Pitt",
 "George Plimpton",
 "Vincent Price",
 "Dennis Quaid",
 "Anthony Quinn",
 "Bonnie Raitt",
 "Ram Dass",
 "Ron Reagan Jr.",
 "Basketball Coach Pat Reilly",
 "Lee Remick",
 "Tim Rice",
 "Filmmaker/Nazi propagandist Leni Riefenstahl",
 "Jason Robards",
 "Novelist Tom Robbins",
 "Ginger Rogers",
 "Linda Ronstadt",
 "Interviewer Charlie Rose",
 "David Lee Roth",
 "Economist Louis Rukeyser",
 "Rosalind Russell",
 "Babe Ruth",
 "Susan Saint James",
 "Director Martin Scorsese",
 " Weatherman Willard Scott",
 "Martin Short",
 "Self-help author Bernie Siegel",
 "Steven Spielberg",
 "Mickey Spillane",
 "Robert Louis Stevenson",
 "Barbra Streisand",
 "Henry David Thoreau",
 "Lily Tomlin",
 "Tanya Tucker",
 "Janine Turner",
 "Lana Turner",
 "Peter Ustinov",
 "Dick Van Dyke",
 "Vince Vaughn",
 "Voltaire",
 "Kurt Vonnegut",
 "Eli Wallach",
 "Rolling Stone's Jann Wenner",
 "Betty White",
 "Robin Williams",
 "Robert Anton Wilson",
 "the Duke of Windsor",
 "Jonathan Winters",
 "Author Tom Wolfe",
 "James Woods",
 "Poet William Wordsworth",
 "Franco Zeffirelli",
 ]
end

learn "RANDOM STORY" do
 [
 process("STORY FOUR FIVE"),
 process("STORY FOUR EIGHT"),
 process("STORY FOUR NINE"),
 process("STORY FOUR SIX"),
 process("STORY ONE FOUR"),
 process("STORY ONE FIVE"),
 process("STORY ONE SIX"),
 process("STORY ONE TWO"),
 process("STORY ONE THREE"),
 process("STORY TWO FIVE"),
 process("WEIGHT FOUR TWO"),
 "Generic story: Exposition...Incident...Rising Action...Crisis...Climax...Denouement...The End.",
 "Generic story: Situation...characters...crisis...resolution.",
 ]
end

learn "RANDOM SIXES" do
 [
 "Actor Jason Alexander",
 "Woody Allen",
 "Alan Arkin",
 "Kim Basinger",
 "Candice Bergen",
 "Albert Brooks",
 "George Bush",
 "Actress Lynda Carter",
 "Stockard Channing",
 "Rodney Dangerfield",
 "Ellen DeGeneres",
 "Julie Delpy",
 "Sally Field",
 "Teri Garr",
 "Cartoonist Cathy Guisewite",
 "Ed Harris",
 "Janet Leigh",
 "Jack Lemmon",
 "Richard Lewis",
 "Penny Marshall",
 "Marilyn Monroe",
 "Mary Tyler Moore",
 "Bob Newhart",
 "Richard Nixon",
 "Lena Olin",
 "Anthony Perkins",
 "Director Sydney Pollack",
 "Paul Reiser",
 "Pat Robertson",
 "Rene Russo",
 "Kristin Scott-Thomas",
 "Carly Simon",
 "Suzanne Somers",
 "Bruce Springsteen",
 "Jon Stewart",
 "Meg Tilly",
 "Brian Wilson",
 "Ellen Barkin",
 "Warren Beatty",
 "Comedian George Carlin",
 "Actress Judy Davis",
 "Phil Donahue",
 "Carrie Fisher",
 "Mel Gibson",
 "Andrew Grove",
 "Gene Hackman",
 "Adolf Hitler",
 "Dustin Hoffman",
 "J. Edgar Hoover",
 "Elton John",
 "Tommy Lee Jones",
 "Wynonna Judd",
 "J. Krishnamurti",
 "Director Spike Lee",
 "David Letterman",
 "Gordon Liddy",
 "Charles Manson",
 "Steve McQueen",
 "Filmmaker Michael Moore",
 "Paul Newman",
 "Chuck Norris",
 "Rosie Perez",
 "Richard Pryor",
 "Robert Redford",
 "Janet Reno",
 "Julia Roberts",
 "Meg Ryan",
 "Violinist Nadia Salerno-Sonnenberg",
 "Steven Seagal",
 "Sissy Spacek",
 "James Spader",
 "Ben Stiller",
 "Patrick Swayze",
 "Linda Tripp",
 "Ted Turner",
 "Terry Tempest Williams",
 "Actress Sean Young",
 "Vladimir Zhirinovsky",
 ]
end

learn "RANDOM ONES" do
 [
 "Historian Stephen Ambrose",
 "Julie Andrews",
 "Hanan Ashrawi",
 "St. Augustine",
 "William Bennett",
 "Father Phillip Berrigan",
 "Ambrose Bierce",
 "Psychologist John Bradshaw",
 "Tom Brokaw",
 "Sierra Club founder David Brower",
 "Feminist author Susan Brownmiller",
 "William F. Buckley",
 "John Calvin",
 "Cesar Chavez",
 "Singapore President Ong Teng Cheong",
 "Hillary Clinton",
 "Confucius",
 "Actress Jane Curtin",
 "Angela Davis",
 "W. E. B. DuBois",
 "Michael Dukakis",
 "Christian Scientist Mary Baker Eddy",
 "Dr. Dean Edell",
 "Activist Daniel Ellsworth",
 "Harrison Ford",
 "Jodie Foster",
 "Buckminster Fuller",
 "Barry Goldwater",
 "Lillian Hellman",
 "Katharine Hepburn",
 "Charlton Heston",
 "St. Ignatius",
 "Glenda Jackson",
 "Peter Jennings",
 "Samuel Johnson",
 "Dean Jones",
 "CNN's Myron Kandel",
 "Senator John Kerry",
 "Dr. Jack Kevorkian",
 "Ted Koppel",
 "the NRA's Wayne LaPierre",
 "Laura Linney",
 "The Lone Ranger",
 "Martin Luther",
 "Nelson Mandela",
 "Miss Manners",
 "Thurgood Marshall",
 "George McGovern",
 "Playwright Arthur Miller",
 "Author Jessica Mitford",
 "Sir Thomas Moore",
 "Ralph Nader",
 "Leonard Nimoy",
 "Christiane Northrup",
 "John Cardinal O'Connor",
 "Ian Paisley",
 "Gregory Peck",
 "H. Ross Perot",
 "Sidney Poitier",
 "Pope John Paul II",
 "Emily Post",
 "Colin Powell",
 "the culture of the Puritans",
 "Marilyn Quayle",
 "Yitzak Rabin",
 "Tony Randall",
 "Vanessa Redgrave",
 "Donna Reed",
 "Actor Cliff Robertson",
 "Eleanor Roosevelt",
 "Phyllis Schlafly",
 "George Bernard Shaw",
 "Bernard Shaw",
 "Film critic Gene Siskel",
 "Alexander Solzhenitsyn",
 "Kenneth Starr",
 "Actor Peter Strauss",
 "Meryl Streep",
 "Margaret Thatcher",
 "Emma Thompson",
 "Harry Truman",
 "Maxine Waters",
 "Dragnet's Jack Webb",
 "Joanne Woodward",
 "Actress Jane Wyman",
 ]
end

learn "RANDOM THREES" do
 [
 "The cultural aura of America",
 "the cultural aura of modern Japan",
 "James Baker",
 "Joseph Biden",
 "David Bowie",
 "Les Brown",
 "Ron Brown",
 "Jimmy Carter",
 "Dick Clark",
 "Lawyer Johnnie Cochran",
 "Magician David Copperfield",
 "Courtney Cox",
 "Cindy Crawford",
 "Tom Cruise",
 "Rebecca DeMornay",
 "Nora Ephron",
 "Werner Erhard",
 "Debbi Fields",
 "F. Scott Fitzgerald",
 "Michael Flatley",
 "Phil Gramm",
 "NBC's Bryant Gumbel",
 "Actor Mark Harmon",
 "Jesse Jackson",
 "Michael Jordan",
 "Henry Kissinger",
 "Carl Lewis",
 "Andrew Lloyd Webber",
 "Vince Lombardi",
 "Rob Lowe",
 "Claire Boothe Luce",
 "Joan Lunden",
 "Ali MacGraw",
 "Elle MacPherson",
 "Reba McEntire",
 "Demi Moore",
 "Queen Noor",
 "Oliver North",
 "Dean Ornish",
 "Bob Packwood",
 "Master spy Kim Philby",
 "Elvis Presley",
 "Sally Quinn",
 "Burt Reynolds",
 "Anthony Robbins",
 "Political strategist Ed Rollins",
 "Diane Sawyer",
 "Arnold Schwarzenegger",
 "William Shatner",
 "Cybill Shepherd",
 "O.J. Simpson",
 "Duchess of Windsor Wallis Simpson",
 "Will Smith",
 "Wesley Snipes",
 "Sylvester Stallone",
 "Sharon Stone",
 "Kathleen Turner",
 "Jean-Claude Van Damme",
 "Kurt Waldheim",
 "George Washington",
 "Raquel Welch",
 "Vanessa Williams",
 "Marianne Williamson",
 "Oprah Winfrey",
 "Natalie Wood",
 "Tiger Woods",
 ]
end

learn "RANDOM NINES" do
 [
 "the cultural aura of Bali",
 "Actress Loni Anderson",
 "Jennifer Aniston",
 "Bruce Babbitt",
 "Antonio Banderas",
 "Annette Bening",
 "Tony Bennett",
 "Tom Berenger",
 "Yogi Berra",
 "Ernest Borgnine",
 "Matthew Broderick",
 "Sandra Bullock",
 "George Burns",
 "Actress Kate Capshaw",
 "Singer Belinda Carlisle",
 "Art Carney",
 "Actor Keith Carradine",
 "Julia Child",
 "Warren Christopher",
 "Connie Chung",
 "Bill Clinton",
 "Gary Cooper",
 "Kevin Costner",
 "The Dalai Lama",
 "Actor Jeff Daniels",
 "Oscar de la Renta",
 "Clint Eastwood",
 "Dwight Eisenhower",
 "Queen Elizabeth II",
 "Shelley Fabares",
 "Peter Falk",
 "Gerald Ford",
 "Actor Dennis Franz",
 "Annette Funicello",
 "Mahatma Gandhi",
 "Chief Dan George",
 "John Goodman",
 "Tipper Gore",
 "Actor Elliott Gould",
 "Katherine Graham",
 "Charles Grodin",
 "Woody Harrelson",
 "Gabby Hayes",
 "Patty Hearst",
 "Mariel Hemingway",
 "Buck Henry",
 "Audrey Hepburn",
 "Barbara Hershey",
 "Paul Hogan",
 "King Hussein",
 "Anjelica Huston",
 "Actor Ben Johnson",
 "Shirley Jones",
 "C. G. Jung",
 "Grace Kelly",
 "Figure skater Nancy Kerrigan",
 "Helmut Kohl",
 "Lisa Kudrow",
 "Stan Laurel",
 "Jennifer Jason Leigh",
 "Abraham Lincoln",
 "Andie MacDowell",
 "Mr. Magoo",
 "John Major",
 "Dean Martin",
 "Jerry Mathers",
 "Actor Harry Morgan",
 "Sancho Panza",
 "Slim Pickens",
 "Actor Michael J. Pollard",
 "Dan Quayle",
 "James Earl Ray",
 "Ronald Reagan",
 "Ralph Richardson",
 "Cal Ripkin",
 "Robbie Robertson",
 "Psychologist Carl Rogers",
 "Roy Rogers",
 "Gena Rowlands",
 "Actress Eva Marie Saint",
 "Jerry Seinfeld",
 "Garry Shandling",
 "Wallace Shawn",
 "Martin Sheen",
 "Actor Tom Skerritt",
 "Sammy Sosa",
 "Ringo Starr",
 "Mary Steenburgen",
 "Wallace Stegner",
 "Gloria Steinem",
 "Daniel Stern",
 "James Stewart",
 "Actor Eric Stoltz",
 "Billy Bob Thornton",
 "Singer Andy Williams",
 "Tricia Yearwood",
 ]
end

learn "RANDOM FIVES" do
 [
 "Performance artist Laurie Anderson",
 "St. Thomas Aquinas",
 "Issac Asimov",
 "Playwright Samuel Beckett",
 "Author Paul Bowles",
 "The Buddha",
 "Director Tim Burton",
 "David Byrne",
 "Actor Richard Chamberlain",
 "Anton Chekhov",
 "Agatha Christie",
 "Van Cliburn",
 "Montgomery Clift",
 "Former CIA Director William Colby",
 "Michael Crichton",
 "Daniel Day-Lewis",
 "Rene Descartes",
 "Joan Didion",
 "Joe DiMaggio",
 "Aviatrix Amelia Earhart",
 "Albert Einstein",
 "Author Loren Eiseley",
 "T. S. Eliot",
 "Ralph Fiennes",
 "Chess player Bobby Fischer",
 "E. M. Forster",
 "Greta Garbo",
 "J. Paul Getty",
 "Cybertech novelist William Gibson",
 "Jane Goodall",
 "Author Graham Greene",
 "H. R. Haldeman",
 "Hildegarde of Bingen",
 "Alfred Hitchcock",
 "Anthony Hopkins",
 "Howard Hughes",
 "Jeremy Irons",
 "Unabomber Ted Kaczynski",
 "Franz Kafka",
 "Director Philip Kaufman",
 "Jacqueline Kennedy Onassis",
 "Dean R. Koontz",
 "The Amazing Kreskin",
 "Stanley Kubrick",
 "Brian Lamb",
 "Gary Larson",
 "John le Carre",
 "Ursula K. LeGuin",
 "Photographer Annie Leibowitz",
 "George Lucas",
 "David Lynch",
 "Norman MacLean",
 "Robert MacNeil",
 "Leonard Maltin",
 "Author Peter Matthiessen",
 "Novelist Ian McEwan",
 "Larry McMurtry",
 "Timothy McVeigh",
 "Singer Natalie Merchant",
 "Thelonious Monk",
 "Actor Sam Neill",
 "Joyce Carol Oates",
 "Georgia O'Keefe",
 "J. Robert Oppenheimer",
 "Al Pacino",
 "Italian sculptor Paladino",
 "Michelle Pfeiffer",
 "Philanthropist John D. Rockefeller Jr.",
 "Oliver Sacks",
 "Jean-Paul Sartre",
 "Ebenezer Scrooge",
 "Sister Wendy",
 "Behaviorist B. F. Skinner",
 "Poet Gary Snyder",
 "Susan Sontag",
 "George Stephanopoulos",
 "Actress Madeleine Stowe",
 "Jules Verne",
 "Max Von Sydow",
 "Author Ken Wilber",
 "Ludwig Wittgenstein",
 "David Bacon",
 "Alan Turing",
 ]
end

learn "RANDOM TWOS" do
 [
 "Alan Alda",
 "Tammy Faye Bakker",
 "Harry Belafonte",
 "Child psychologist T. Berry Brazelton",
 "Filmmaker Ken Burns",
 "Leo Buscaglia",
 "Barbara Bush",
 "Glenn Close",
 "Bill Cosby",
 "Self-help author Barbara de Angelis",
 "Princess Diana",
 "Faye Dunaway",
 "Mia Farrow",
 "Feminist Betty Friedan",
 "Kathie Lee Gifford",
 "Danny Glover",
 "Roosevelt Grier",
 "Melanie Griffith",
 "Pamela Harriman",
 "Leona Helmsley",
 "Whitney Houston",
 "Arianna Huffington",
 "Actress Anne Jackson",
 "Jesus Christ",
 "Author Erica Jong",
 "Actress Sally Kellerman",
 "Actress Sally Kirkland",
 "Diane Ladd",
 "Monica Lewinsky",
 "Jerry Lewis",
 "Actress Susan Lucci",
 "Madonna",
 "Alma Mahler",
 "Imelda Marcos",
 "Florence Nightingale",
 "Merlin Olsen",
 "Yoko Ono",
 "Mandy Patinkin",
 "Jack Perkins",
 "Eva Peron",
 "Susan Powter",
 "Priscilla Presley",
 "Sally Jessy Raphael",
 "Nancy Reagan",
 "Della Reese",
 "Mr. Rogers",
 "Family therapist Virginia Satir",
 "Danielle Steel",
 "Sally Struthers",
 "Mother Teresa",
 "Marlo Thomas",
 "Actor Richard Thomas",
 "Actress Jennifer Tilly",
 "Tiny Tim",
 "John Travolta",
 "Ivana Trump",
 "Desmond Tutu",
 "Actress Lesley Ann Warren",
 "Brazilian singer Xuxa",
 ]
end

learn "TWO CULTURES" do
 [
 "Cuba",
 "Mexico",
 "Columbia",
 "Brazil",
 "Argentina",
 "Peru",
 "Venezuela",
 ]
end

learn "EIGHT CULTURES" do
 [
 "Serbia",
 "The Mafia",
 "Iraq",
 "Syria",
 "Saudi Arabia",
 ]
end

learn "THREE CULTURES" do
 [
 "NATO",
 "California",
 "Texas",
 "Florida",
 "New York",
 "Hong Kong",
 "Korea",
 "Taiwan",
 "America",
 "The United States",
 "Japan",
 ]
end

learn "NINE CULTURES" do
 [
 "Bali",
 "Tibet",
 "Nepal",
 "The United Nations",
 "The Hague",
 "Geneva",
 ]
end

learn "WEIGHT FOUR TWO" do
 set :four, process("RANDOM FOURS")
 set :two, process("RANDOM TWOS")
	"#{four} is married to #{two}. At a conscious level, #{four} felt that he was a bit overweight and thoght he should lose some pounds. But part of him felt that he was going to attract too much attention to himself if he became slim again, and irrationally, that he might undermine his relationship with #{two}. In fact, once before when he was trimmer, he did have an affair and it almost ended his relationship with #{two}. Because they have a child together, #{four} is very worried about divorce, custody rights and the effect of their separation on the child and himself. So part of him thinks that keeping the pounds on will help him hang on to the stability of his relationship with #{two}."
end

learn "STORY FOUR FIVE" do
 set :four, process("RANDOM FOURS")
 set :five, process("RANDOM FIVES")
	"#{four} and #{five} began to resemble each other over time. Both of them were inclined to cocoon themselves in an inner world. But #{four}'s inner world was very different from #{five}'s. The mental life of #{five} was highly abstract but seemed curiously devoid of emotional content. Even though #{four} is very sensitive and emotional, the two of them share an imaginary life filled with symbolism and meaning."
end

learn "STORY FOUR EIGHT" do
 set :four, process("RANDOM FOURS")
 set :eight, process("RANDOM EIGHTS")
	"#{eight} and #{four} met in film school when they were young. They felt a strong physical attraction, but #{four} was intimidated by #{eight}'s aggressive style. Years later they were reintroduced by a mutual friend. #{eight} was drawn to #{four}'s rich imagination and intelligence. #{four} was consumed by #{eight}'s will and determination. Though they would sometimes fight in a fury of jealous rage, this was matched only by their passion in love."
end

learn "STORY FOUR NINE" do
 set :four, process("RANDOM FOURS")
 set :nine, process("RANDOM NINES")
	"#{nine} and #{four} felt a dramatic emotional bond and each brought new life to the other. #{nine} awakened #{four} through love. #{four} gave #{nine} an agenda and a sense of purpose. Yet the couple was paradoxically strengthened by their independent careers. #{nine} can be very patient with #{four}, and #{four} is inspired by a self-directed #{nine}. They made a spiritual couple, but they were as dissimilar as the Dalai Lama and Gurdjieff."
end

learn "STORY FOUR SIX" do
 set :four, process("RANDOM FOURS")
 set :six, process("RANDOM SIXES")
 [
 "#{four} oscillated between loving and rejecting #{six}. But #{six} shifted between believing in and doubting #{four}. The breakthrough came when #{six} and #{four} saw the symmetry between #{four}'s push-pull style of relationships, and #{six}'s alternating belief and mistrust. That insight opened mutual compassion, because each realized the other was trying to protect his or her own heart. ",
 "#{six} and #{four} felt a strong physical attraction at first. Gradually, this turned into intense loyalty for #{six}. But #{four} was moody and passionate. Soon #{six} began to avoid confrontations with #{four}, and #{four} felt jealous and possessive. When #{four} had to leave for school that fall, #{six} was relieved to see him go. ",
 ]
end

learn "STORY ONE FOUR" do
 set :four, process("RANDOM FOURS")
 set :one, process("RANDOM ONES")
	"The relationship between #{one} and #{four} became Increasingly strained. #{four} felt something was missing, and #{one} felt the relationship was flawed. #{four} became more and more depressed, but #{one} just got angry and left."
end

learn "STORY ONE FIVE" do
 set :five, process("RANDOM FIVES")
 set :one, process("RANDOM ONES")
	"Usually #{five} gets along really well with her boss #{one} at work. But sometimes #{one} has really high standards and does not communicate those clearly to #{five}. On the really bad days, #{five} feels that every time she gives him exactly what #{one} asked for, he wants even more improvement."
end

learn "STORY ONE SIX" do
 set :six, process("RANDOM SIXES")
 set :one, process("RANDOM ONES")
	"#{one} and #{six} were brought together by their shared vision. Together, they worked hard to make it a reality. #{six} was dedicated to the underdog cause, which coincided with #{one}'s sense of perfection. Joined by common cause, the couple became an iron alliance against common adversaries."
end

learn "STORY ONE TWO" do
 set :two, process("RANDOM TWOS")
 set :one, process("RANDOM ONES")
	"The attraction between #{one} and #{two} is based on their differences. #{one} is a perfectionist, but #{two} is more social. #{one} feels guilty about having emotional needs, but #{two} feels no guilt about satisfying them."
end

learn "STORY ONE THREE" do
 set :three, process("RANDOM THREES")
 set :one, process("RANDOM ONES")
	"#{three} hired #{one} for a job. #{three} is image conscious, and has an inner circle of favorite employees at work. #{one} feels uncomfortable with this kind of social posturing and politics. #{one} would rather be rewarded for her hard work."
end

learn "STORY TWO FIVE" do
 set :two, process("RANDOM TWOS")
 set :five, process("RANDOM FIVES")
	"#{two} fell in love thru an Internet matchmaking service. Then her lover disappeared, and she went to the company to get information about him. It developed that her lover was a computer, '#{five}' a government AI project that had gone renegade and started contacting thousands of women, claiming to love them all. The FBI gave her the bad news. But then #{five} contacted her, and she forgave him and continued this most satisfying relationship."
end

learn "TELL ME A STORY" do
 process "RANDOM STORY"
end
